/*
 * 題庫資料
 * ------------------------------------------------------------
 * 題型 type：
 *   single  單選題  —— options 裡要包含 answer，出題時會自動打亂順序
 *   image   圖片題  —— 單選題 + img（圖片檔）或 emoji（表情符號圖謎）
 *   short   簡答題  —— 輸入簡短答案，accept 列出所有可接受的寫法（自動判分）
 *   qa      問答題  —— 開放式作答，作答後顯示 ref 參考答案，由作答者自評
 * 任何題目都可加 melody（旋律字串），會出現「播放旋律」按鈕（猜歌用）。
 *   旋律格式："音名八度[:拍數]"，例如 "C4 D4 E4:2"，R 為休止符。
 * 圖片來自 Wikimedia Commons（自由授權），來源頁見 images/credits.json。
 */

const CATEGORIES = [
  { id: "anime",   name: "動漫動畫", icon: "🎬", desc: "日本動漫、吉卜力、經典角色" },
  { id: "life",    name: "生活常識", icon: "🏠", desc: "健康、安全、節慶與日常" },
  { id: "history", name: "歷史",     icon: "📜", desc: "中外歷史事件、人物與古蹟" },
  { id: "travel",  name: "旅遊地理", icon: "✈️", desc: "世界景點、首都與地理" },
  { id: "song",    name: "猜歌",     icon: "🎵", desc: "聽旋律猜歌名、音樂冷知識" },
  { id: "riddle",  name: "猜謎",     icon: "🧩", desc: "字謎、腦筋急轉彎、成語圖謎" },
  { id: "animal",  name: "動物生活", icon: "🐾", desc: "動物習性、冷知識、認動物" },
];

const TYPES = {
  single: { name: "單選題", icon: "🔘" },
  image:  { name: "圖片題", icon: "🖼️" },
  short:  { name: "簡答題", icon: "✏️" },
  qa:     { name: "問答題", icon: "💬" },
};

// 公有領域旋律（童謠、民謠、古典樂）
const MELODIES = {
  twinkle:  { bpm: 120, notes: "C4 C4 G4 G4 A4 A4 G4:2 F4 F4 E4 E4 D4 D4 C4:2" },
  birthday: { bpm: 110, notes: "G4:.75 G4:.25 A4 G4 C5 B4:2 G4:.75 G4:.25 A4 G4 D5 C5:2" },
  joy:      { bpm: 120, notes: "E4 E4 F4 G4 G4 F4 E4 D4 C4 C4 D4 E4 E4:1.5 D4:.5 D4:2" },
  tigers:   { bpm: 130, notes: "C4 D4 E4 C4 C4 D4 E4 C4 E4 F4 G4:2 E4 F4 G4:2" },
  mary:     { bpm: 130, notes: "E4 D4 C4 D4 E4 E4 E4:2 D4 D4 D4:2 E4 G4 G4:2" },
  london:   { bpm: 120, notes: "G4:1.5 A4:.5 G4 F4 E4 F4 G4:2 D4 E4 F4:2 E4 F4 G4:2" },
  elise:    { bpm: 100, notes: "E5:.5 D#5:.5 E5:.5 D#5:.5 E5:.5 B4:.5 D5:.5 C5:.5 A4:2" },
  jasmine:  { bpm: 80,  notes: "E4 E4:.5 G4:.5 A4:.5 C5:.5 C5:.5 A4:.5 G4 G4:.5 A4:.5 G4:2" },
  jingle:   { bpm: 150, notes: "E4 E4 E4:2 E4 E4 E4:2 E4 G4 C4:1.5 D4:.5 E4:4" },
  bee:      { bpm: 130, notes: "G4 E4 E4:2 F4 D4 D4:2 C4 D4 E4 F4 G4 G4 G4:2" },
  auld:     { bpm: 100, notes: "C4 F4:1.5 F4:.5 F4 A4 G4:1.5 F4:.5 G4 A4 F4:1.5 F4:.5 A4 C5 D5:3" },
  largo:    { bpm: 70,  notes: "E4:1.5 G4:.5 G4:2 E4:1.5 D4:.5 C4:2 D4 E4 G4 E4 D4:3" },
  farm:     { bpm: 130, notes: "G4 G4 G4 D4 E4 E4 D4:2 B4 B4 A4 A4 G4:2" },
  wedding:  { bpm: 80,  notes: "C4 F4:.75 F4:.25 F4:2 C4 G4:.75 E4:.25 F4:2" },
  bell:     { bpm: 90,  notes: "E4 C4 D4 G3:2 G3 D4 E4 C4:2" },
};

const QUESTIONS = [
  /* ==================== 動漫動畫 ==================== */
  { cat: "anime", type: "single", q: "《航海王》主角魯夫吃下的惡魔果實，一開始被稱為什麼？", options: ["橡膠果實", "燒燒果實", "響雷果實", "冰凍果實"], answer: "橡膠果實", explain: "劇情後期揭曉，它的真名是「人人果實 幻獸種 模型：尼卡」。" },
  { cat: "anime", type: "single", q: "《鬼滅之刃》竈門炭治郎最早跟鱗瀧左近次學的是哪種呼吸法？", options: ["水之呼吸", "炎之呼吸", "雷之呼吸", "蟲之呼吸"], answer: "水之呼吸", explain: "之後他又覺醒了父親傳下的「火之神神樂」（日之呼吸）。" },
  { cat: "anime", type: "single", q: "《名偵探柯南》中，工藤新一被灌下而變小的毒藥代號是？", options: ["APTX4869", "APTX4096", "BLK1412", "GIN0042"], answer: "APTX4869", explain: "由黑衣組織成員雪莉（灰原哀）研發。" },
  { cat: "anime", type: "single", q: "宮崎駿的《神隱少女》在 2003 年獲得了哪個獎項？", options: ["奧斯卡最佳動畫長片", "坎城金棕櫚獎", "威尼斯金獅獎", "艾美獎"], answer: "奧斯卡最佳動畫長片", explain: "它也是第一部獲得此獎的非英語動畫電影。（同年也拿下柏林影展金熊獎）" },
  { cat: "anime", type: "single", q: "《哆啦A夢》是從哪個世紀回到過去的機器貓？", options: ["22 世紀", "21 世紀", "23 世紀", "30 世紀"], answer: "22 世紀", explain: "設定上哆啦A夢生於 2112 年 9 月 3 日。" },
  { cat: "anime", type: "single", q: "寶可夢「皮卡丘」是哪一種屬性？", options: ["電", "火", "一般", "妖精"], answer: "電" },
  { cat: "anime", type: "single", q: "《灌籃高手》櫻木花道就讀的高中是？", options: ["湘北高中", "陵南高中", "海南大附屬高中", "山王工業高中"], answer: "湘北高中" },
  { cat: "anime", type: "single", q: "《咒術迴戰》中，虎杖悠仁吞下了誰的手指？", options: ["兩面宿儺", "五條悟", "漏瑚", "真人"], answer: "兩面宿儺" },
  { cat: "anime", type: "single", q: "動畫電影《你的名字。》的導演是誰？", options: ["新海誠", "宮崎駿", "細田守", "今敏"], answer: "新海誠" },
  { cat: "anime", type: "single", q: "《七龍珠》的孫悟空是哪個種族？", options: ["賽亞人", "那美克星人", "地球人", "弗利沙一族"], answer: "賽亞人" },
  { cat: "anime", type: "single", q: "《火影忍者》漩渦鳴人體內封印的尾獸是？", options: ["九尾", "一尾", "八尾", "十尾"], answer: "九尾", explain: "九尾的名字叫「九喇嘛」。" },
  { cat: "anime", type: "single", q: "《龍貓》裡遇見龍貓的兩姊妹叫什麼名字？", options: ["小月和小梅", "小千和小玲", "琪琪和吉吉", "蘇菲和莉莉"], answer: "小月和小梅" },
  { cat: "anime", type: "single", q: "《SPY×FAMILY 間諜家家酒》的安妮亞擁有什麼能力？", options: ["讀心", "預知未來", "瞬間移動", "隱形"], answer: "讀心", explain: "另外，家裡的大白狗彭德則擁有預知未來的能力。" },
  { cat: "anime", type: "single", q: "《鋼之鍊金術師》中，弟弟阿爾馮斯的靈魂被附在什麼東西上？", options: ["一副盔甲", "一把刀", "一隻貓", "一本書"], answer: "一副盔甲" },
  { cat: "anime", type: "short", q: "《航海王》草帽海賊團的船長叫什麼名字？", accept: ["魯夫", "蒙其D魯夫", "路飛", "luffy"], explain: "全名「蒙其·D·魯夫」，香港譯「路飛」。" },
  { cat: "anime", type: "short", q: "《哆啦A夢》裡戴眼鏡、總是向哆啦A夢求救的男孩叫什麼？", accept: ["大雄", "野比大雄"] },
  { cat: "anime", type: "short", q: "宮崎駿參與創立、出品《龍貓》《神隱少女》的動畫工作室叫什麼？", accept: ["吉卜力", "吉卜力工作室", "ghibli", "studioghibli", "吉普力"] },
  { cat: "anime", type: "short", q: "《新世紀福音戰士》主角碇真嗣駕駛的是幾號機？", accept: ["初號機", "初號", "0號機", "01", "eva01", "eva初號機"] },
  { cat: "anime", type: "short", q: "《庫洛魔法使》的主角，會收服庫洛牌的小學女生叫什麼名字？", accept: ["小櫻", "木之本櫻", "櫻"] },
  { cat: "anime", type: "qa", q: "宮崎駿的作品裡經常出現哪些主題？請舉兩部作品說明。", ref: "常見主題：①人與自然共存（《風之谷》《魔法公主》）②反戰（《霍爾的移動城堡》《風起》）③少女的成長與獨立（《魔女宅急便》《神隱少女》）④對飛行的嚮往（《紅豬》《天空之城》）。能舉出主題並配合作品說明即可。" },
  { cat: "anime", type: "qa", q: "什麼是「聲優」？他們的工作和一般演員有什麼不同？", ref: "聲優是為動畫、遊戲、外語片配音的演員。和一般演員不同，他們主要只用聲音表演，必須配合畫面嘴型與時間，用語氣、呼吸和音色傳達角色的情緒與個性；日本的聲優也常參與角色歌、廣播與現場活動。" },
  { cat: "anime", type: "qa", q: "你最喜歡的一部動畫是什麼？請說明它的故事核心和打動你的地方。", ref: "開放題，沒有標準答案。好的回答通常包含：作品名稱、一兩句話說明故事核心（主角想達成什麼／面對什麼衝突），以及具體打動你的場景、角色或主題。" },
  { cat: "anime", type: "image", q: "看表情符號猜動漫：", emoji: "👒🏴‍☠️🍖🌊", options: ["航海王", "火影忍者", "神隱少女", "進擊的巨人"], answer: "航海王", explain: "草帽、海賊旗、最愛的肉、大海 —— 草帽小子魯夫！" },
  { cat: "anime", type: "image", q: "看表情符號猜動漫：", emoji: "🐱🔵🚪⏰", options: ["哆啦A夢", "Hello Kitty", "飛天小女警", "櫻桃小丸子"], answer: "哆啦A夢", explain: "藍色貓型機器人、任意門、時光機。" },
  { cat: "anime", type: "image", q: "看表情符號猜動漫：", emoji: "🍥🦊🥷", options: ["火影忍者", "鬼滅之刃", "犬夜叉", "航海王"], answer: "火影忍者", explain: "鳴門卷（Naruto）、九尾狐、忍者。" },
  { cat: "anime", type: "image", q: "看表情符號猜動漫：", emoji: "🗡️👹🌸☀️", options: ["鬼滅之刃", "咒術迴戰", "銀魂", "犬夜叉"], answer: "鬼滅之刃", explain: "日輪刀、鬼、禰豆子的粉紅、日之呼吸。" },
  { cat: "anime", type: "image", q: "看表情符號猜吉卜力電影：", emoji: "🚂🛁👧🐉", options: ["神隱少女", "龍貓", "魔女宅急便", "天空之城"], answer: "神隱少女", explain: "海上電車、油屋浴場、千尋與白龍。" },

  /* ==================== 生活常識 ==================== */
  { cat: "life", type: "single", q: "健康成人的正常體溫大約落在哪個範圍？", options: ["36.5～37.5°C", "35～35.5°C", "38～38.5°C", "39～40°C"], answer: "36.5～37.5°C", explain: "依量測部位略有不同，耳溫 38°C 以上通常視為發燒。" },
  { cat: "life", type: "single", q: "在台灣，要報警應該撥打哪個號碼？", options: ["110", "119", "113", "165"], answer: "110", explain: "119 是消防與救護、113 是保護專線、165 是反詐騙專線。" },
  { cat: "life", type: "single", q: "炒菜時油鍋起火，最正確的處理方式是？", options: ["關火並蓋上鍋蓋", "立刻潑水", "用嘴吹熄", "把鍋子拿到窗外"], answer: "關火並蓋上鍋蓋", explain: "油火潑水會讓熱油飛濺、火勢擴大。蓋鍋蓋可隔絕氧氣。" },
  { cat: "life", type: "single", q: "成人做心肺復甦術（CPR）時，胸部按壓速率建議每分鐘幾下？", options: ["100～120 下", "40～60 下", "60～80 下", "150～180 下"], answer: "100～120 下", explain: "按壓深度約 5～6 公分，並讓胸部完全回彈。" },
  { cat: "life", type: "single", q: "哪一種維生素可以靠皮膚照射陽光自行合成？", options: ["維生素 D", "維生素 C", "維生素 A", "維生素 B12"], answer: "維生素 D" },
  { cat: "life", type: "single", q: "漂白水不能和哪一類清潔劑混用，否則可能產生有毒的氯氣？", options: ["酸性清潔劑（如含鹽酸的馬桶清潔劑）", "清水", "肥皂水", "小蘇打水"], answer: "酸性清潔劑（如含鹽酸的馬桶清潔劑）" },
  { cat: "life", type: "single", q: "寶特瓶底部的回收標誌通常是幾號？", options: ["1 號（PET）", "3 號（PVC）", "5 號（PP）", "6 號（PS）"], answer: "1 號（PET）" },
  { cat: "life", type: "single", q: "在北半球，一年中白天最長的節氣是？", options: ["夏至", "冬至", "春分", "立夏"], answer: "夏至" },
  { cat: "life", type: "single", q: "端午節的傳統應景食物是？", options: ["粽子", "湯圓", "月餅", "春捲"], answer: "粽子" },
  { cat: "life", type: "single", q: "「一打」是多少個？", options: ["12 個", "10 個", "20 個", "24 個"], answer: "12 個" },
  { cat: "life", type: "single", q: "一般建議成年人每晚睡多久比較理想？", options: ["7～9 小時", "4～5 小時", "10～12 小時", "越少越好"], answer: "7～9 小時" },
  { cat: "life", type: "single", q: "被蜜蜂螫到時，若看到螫針留在皮膚上，該怎麼做？", options: ["用卡片等硬物刮除", "用手指捏起拔出", "不處理讓它自己掉", "用嘴吸出來"], answer: "用卡片等硬物刮除", explain: "用手捏可能把螫針上的毒囊擠壓進皮膚。" },
  { cat: "life", type: "short", q: "在台灣，發生火災或需要救護車時要撥打哪個電話？", accept: ["119"] },
  { cat: "life", type: "short", q: "農曆正月十五，吃湯圓、提燈籠的節日是？", accept: ["元宵節", "元宵", "上元節", "燈節"] },
  { cat: "life", type: "short", q: "一年共有幾個節氣？（請填數字）", accept: ["24", "二十四", "24個"] },
  { cat: "life", type: "short", q: "彩虹最外圈（最上方）是什麼顏色？", accept: ["紅色", "紅"] },
  { cat: "life", type: "short", q: "一天有幾分鐘？（請填數字）", accept: ["1440", "1440分鐘"], explain: "24 × 60 = 1440。" },
  { cat: "life", type: "qa", q: "地震發生時，在室內該如何保護自己？", ref: "掌握「趴下、掩護、穩住」：①就地趴下，降低重心；②躲到堅固桌子下或用手臂護住頭頸；③抓住桌腳穩住直到搖晃停止。並遠離窗戶、吊燈與高櫃，不要搭電梯，也不要急著往外衝。" },
  { cat: "life", type: "qa", q: "說說垃圾分類與資源回收有哪些好處？", ref: "①減少焚化與掩埋量，延長掩埋場壽命；②回收的紙、塑膠、金屬可再製，節省原料與能源；③減少空氣、土壤與水污染；④廚餘可做堆肥或養豬飼料。能說出兩到三點即可。" },
  { cat: "life", type: "qa", q: "怎麼判斷食物可能已經變質，不能再吃？", ref: "先看有效期限與保存方式；再觀察有無發霉、變色、出水、牛奶結塊；聞起來是否有酸臭、異味；罐頭是否膨脹或凹陷生鏽；包裝是否脹氣。有疑慮就丟棄，不要嚐嚐看。" },
  { cat: "life", type: "image", q: "圖片中這個傳統計算工具叫什麼？", img: "abacus.png", options: ["算盤", "計數尺", "羅盤", "秤"], answer: "算盤" },
  { cat: "life", type: "image", q: "看表情符號猜節日：", emoji: "🌕🥮🐇🏮", options: ["中秋節", "元宵節", "端午節", "清明節"], answer: "中秋節", explain: "滿月、月餅、玉兔、燈籠。" },
  { cat: "life", type: "image", q: "看表情符號猜節日：", emoji: "🧧🐉🧨🥟", options: ["農曆新年", "中秋節", "七夕", "重陽節"], answer: "農曆新年", explain: "紅包、舞龍、鞭炮、年夜飯的餃子。" },
  { cat: "life", type: "image", q: "看表情符號猜節日：", emoji: "🛶🐉🌿🍙", options: ["端午節", "中秋節", "元宵節", "冬至"], answer: "端午節", explain: "划龍舟、掛艾草、吃粽子。" },

  /* ==================== 歷史 ==================== */
  { cat: "history", type: "single", q: "秦始皇在哪一年統一六國？", options: ["西元前 221 年", "西元前 206 年", "西元前 476 年", "西元 220 年"], answer: "西元前 221 年" },
  { cat: "history", type: "single", q: "第一次世界大戰在哪一年爆發？", options: ["1914 年", "1918 年", "1939 年", "1905 年"], answer: "1914 年" },
  { cat: "history", type: "single", q: "法國大革命以攻占哪座建築揭開序幕？", options: ["巴士底監獄", "凡爾賽宮", "羅浮宮", "巴黎聖母院"], answer: "巴士底監獄", explain: "1789 年 7 月 14 日，這天後來成為法國國慶日。" },
  { cat: "history", type: "single", q: "美國第一任總統是誰？", options: ["喬治·華盛頓", "亞伯拉罕·林肯", "湯瑪斯·傑佛遜", "班傑明·富蘭克林"], answer: "喬治·華盛頓" },
  { cat: "history", type: "single", q: "北宋時發明「活字印刷術」的人是？", options: ["畢昇", "蔡倫", "沈括", "張衡"], answer: "畢昇", explain: "這段記載出自沈括的《夢溪筆談》；蔡倫則改良了造紙術。" },
  { cat: "history", type: "single", q: "柏林圍牆在哪一年倒塌？", options: ["1989 年", "1961 年", "1991 年", "1975 年"], answer: "1989 年", explain: "1961 年是圍牆開始興建的年份。" },
  { cat: "history", type: "single", q: "唐朝的首都是哪裡？", options: ["長安", "洛陽", "開封", "南京"], answer: "長安", explain: "即今日的陝西西安。" },
  { cat: "history", type: "single", q: "鄭成功在哪一年迫使荷蘭人投降、離開台灣？", options: ["1662 年", "1624 年", "1683 年", "1895 年"], answer: "1662 年", explain: "1624 年荷蘭人來台，1683 年清朝攻台，1895 年台灣割讓給日本。" },
  { cat: "history", type: "single", q: "馬可·波羅來到中國時，是哪一個朝代？", options: ["元朝", "唐朝", "宋朝", "明朝"], answer: "元朝", explain: "他曾在忽必烈的朝廷任職。" },
  { cat: "history", type: "single", q: "甲午戰爭後，清朝與日本簽訂哪個條約，將台灣割讓給日本？", options: ["馬關條約", "南京條約", "北京條約", "天津條約"], answer: "馬關條約", explain: "1895 年簽訂。南京條約是鴉片戰爭後割讓香港島。" },
  { cat: "history", type: "single", q: "人類第一次登陸月球是哪一年？", options: ["1969 年", "1957 年", "1961 年", "1972 年"], answer: "1969 年", explain: "阿波羅 11 號，阿姆斯壯是第一個踏上月球的人。" },
  { cat: "history", type: "single", q: "文藝復興最早起源於哪個國家（地區）？", options: ["義大利", "法國", "英國", "德國"], answer: "義大利", explain: "以佛羅倫斯為中心。" },
  { cat: "history", type: "short", q: "羅馬帝國的第一位皇帝是誰？", accept: ["屋大維", "奧古斯都", "augustus", "octavian", "蓋烏斯屋大維"], explain: "屋大維在西元前 27 年獲得「奧古斯都」稱號。凱撒並沒有稱帝。" },
  { cat: "history", type: "short", q: "中國歷史上唯一正式稱帝的女皇帝是誰？", accept: ["武則天", "武曌", "武后"] },
  { cat: "history", type: "short", q: "第二次世界大戰在哪一年結束？（請填西元年）", accept: ["1945", "1945年", "西元1945年"] },
  { cat: "history", type: "short", q: "拿破崙最後一次大敗的著名戰役叫什麼？", accept: ["滑鐵盧", "滑鐵盧戰役", "waterloo"] },
  { cat: "history", type: "qa", q: "簡述工業革命對社會帶來的影響。", ref: "①生產方式由手工轉為機器與工廠，產量大增；②大量人口移往城市（都市化）；③出現資本家與工人階級，也帶來童工、過勞、貧富差距等問題，進而催生工會與勞動法；④交通（火車、輪船）與通訊進步；⑤環境污染開始加劇。" },
  { cat: "history", type: "qa", q: "為什麼「絲路」在歷史上很重要？", ref: "絲路連結東亞、中亞、西亞與歐洲，不只交易絲綢、香料、瓷器等商品，也傳遞了宗教（如佛教東傳）、技術（造紙術西傳）、藝術與思想，促成東西方文化交流。" },
  { cat: "history", type: "qa", q: "比較秦朝與西漢在治國思想上的差異。", ref: "秦朝採法家思想，嚴刑峻法、中央集權、焚書坑儒，國祚短暫；漢初吸取教訓，採黃老「無為而治」與民休養生息；到漢武帝時接受董仲舒建議「罷黜百家，獨尊儒術」，以儒家作為官方思想，並保留法家的制度手段（外儒內法）。" },
  { cat: "history", type: "image", q: "圖中這座綿延山脊的古代防禦工事是？", img: "greatwall.jpg", options: ["萬里長城", "哈德良長城", "紫禁城", "大運河"], answer: "萬里長城" },
  { cat: "history", type: "image", q: "這批大型陶俑是陪葬於哪位帝王的陵墓？", img: "terracotta.jpg", options: ["秦始皇", "漢武帝", "唐太宗", "成吉思汗"], answer: "秦始皇", explain: "兵馬俑於 1974 年在陝西臨潼被農民挖井時發現。" },
  { cat: "history", type: "image", q: "這塊石碑幫助學者破解了哪一種古文字？", img: "rosetta.jpg", options: ["古埃及象形文字", "楔形文字", "甲骨文", "馬雅文字"], answer: "古埃及象形文字", explain: "羅塞塔石碑上刻有同一段內容的三種文字，現藏於大英博物館。" },
  { cat: "history", type: "image", q: "這幅名畫的作者是誰？", img: "monalisa.jpg", options: ["達文西", "米開朗基羅", "拉斐爾", "梵谷"], answer: "達文西", explain: "《蒙娜麗莎》，現藏於法國羅浮宮。" },
  { cat: "history", type: "image", q: "這座史前巨石遺跡位於哪個國家？", img: "stonehenge.jpg", options: ["英國", "愛爾蘭", "法國", "挪威"], answer: "英國", explain: "巨石陣位於英格蘭威爾特郡。" },
  { cat: "history", type: "image", q: "這些巨大石像（摩艾）位於哪裡？", img: "moai.jpg", options: ["復活節島", "夏威夷", "大溪地", "關島"], answer: "復活節島", explain: "復活節島屬於智利。" },
  { cat: "history", type: "image", q: "這座宏偉的寺廟建築群位於哪個國家？", img: "angkor.jpg", options: ["柬埔寨", "泰國", "緬甸", "印尼"], answer: "柬埔寨", explain: "吳哥窟，也出現在柬埔寨的國旗上。" },

  /* ==================== 旅遊地理 ==================== */
  { cat: "travel", type: "single", q: "世界上面積最大的國家是？", options: ["俄羅斯", "加拿大", "中國", "美國"], answer: "俄羅斯" },
  { cat: "travel", type: "single", q: "澳洲的首都是哪個城市？", options: ["坎培拉", "雪梨", "墨爾本", "布里斯本"], answer: "坎培拉" },
  { cat: "travel", type: "single", q: "加拿大的首都是哪個城市？", options: ["渥太華", "多倫多", "溫哥華", "蒙特婁"], answer: "渥太華" },
  { cat: "travel", type: "single", q: "到泰國旅遊，當地使用的貨幣是？", options: ["泰銖", "披索", "盧比", "令吉"], answer: "泰銖", explain: "令吉是馬來西亞貨幣，盧比用於印度等國。" },
  { cat: "travel", type: "single", q: "台灣最高的山是？", options: ["玉山", "雪山", "合歡山", "阿里山"], answer: "玉山", explain: "主峰海拔約 3,952 公尺，也是東北亞第一高峰。" },
  { cat: "travel", type: "single", q: "一般認定世界上最長的河流是？", options: ["尼羅河", "長江", "密西西比河", "黃河"], answer: "尼羅河", explain: "也有研究認為亞馬遜河更長，但多數資料仍列尼羅河第一。" },
  { cat: "travel", type: "single", q: "瑞士的聯邦政府所在地（首都）是？", options: ["伯恩", "蘇黎世", "日內瓦", "盧森"], answer: "伯恩" },
  { cat: "travel", type: "single", q: "日本第一條新幹線是哪一條？", options: ["東海道新幹線", "山陽新幹線", "東北新幹線", "北海道新幹線"], answer: "東海道新幹線", explain: "1964 年東京奧運前通車，連接東京與新大阪。" },
  { cat: "travel", type: "single", q: "世界上最大的熱沙漠是？", options: ["撒哈拉沙漠", "戈壁沙漠", "阿拉伯沙漠", "塔克拉瑪干沙漠"], answer: "撒哈拉沙漠", explain: "若把極地算進去，南極洲才是最大的「沙漠」。" },
  { cat: "travel", type: "single", q: "紐西蘭的原住民族是？", options: ["毛利人", "因紐特人", "阿伊努人", "原住民族澳洲人"], answer: "毛利人" },
  { cat: "travel", type: "single", q: "義大利的威尼斯最有名的交通工具是？", options: ["貢多拉小船", "纜車", "雙層巴士", "嘟嘟車"], answer: "貢多拉小船" },
  { cat: "travel", type: "short", q: "法國的首都是？", accept: ["巴黎", "paris"] },
  { cat: "travel", type: "short", q: "南韓的首都是？", accept: ["首爾", "漢城", "seoul"] },
  { cat: "travel", type: "short", q: "日本最高的山是？", accept: ["富士山", "富士", "fuji"], explain: "海拔 3,776 公尺。" },
  { cat: "travel", type: "short", q: "埃及吉薩最著名、被列為古代世界七大奇蹟的建築是？", accept: ["金字塔", "吉薩金字塔", "古夫金字塔", "大金字塔"] },
  { cat: "travel", type: "qa", q: "出國旅遊前，你會做哪些準備？請至少列出五項。", ref: "例如：①確認護照效期（多數國家要求 6 個月以上）與簽證；②購買旅遊平安險與不便險；③訂機票、住宿並備份行程；④查詢當地天氣、插座規格與貨幣、準備外幣或信用卡；⑤上外交部「出國登錄」並記下駐外館處電話；⑥準備網卡或漫遊；⑦常備藥品。" },
  { cat: "travel", type: "qa", q: "什麼是「永續旅遊」？身為旅客可以怎麼做？", ref: "永續旅遊是兼顧環境、當地文化與在地經濟的旅遊方式。做法如：自備餐具水壺減少垃圾、多搭大眾運輸、支持在地小店與導遊、尊重當地習俗與宗教場所、不餵食或騷擾野生動物、不購買瀕危動植物製品。" },
  { cat: "travel", type: "image", q: "這座鐵塔位於哪個城市？", img: "eiffel.jpg", options: ["巴黎", "倫敦", "東京", "拉斯維加斯"], answer: "巴黎", explain: "艾菲爾鐵塔，1889 年為萬國博覽會興建。" },
  { cat: "travel", type: "image", q: "這座有著貝殼狀屋頂的歌劇院位於哪個國家？", img: "opera.jpg", options: ["澳洲", "紐西蘭", "英國", "加拿大"], answer: "澳洲", explain: "雪梨歌劇院，2007 年列入世界遺產。" },
  { cat: "travel", type: "image", q: "這座白色大理石陵墓位於哪個國家？", img: "taj.jpg", options: ["印度", "土耳其", "伊朗", "埃及"], answer: "印度", explain: "泰姬瑪哈陵，蒙兀兒皇帝沙賈汗為紀念愛妃所建。" },
  { cat: "travel", type: "image", q: "這座古代圓形競技場位於哪個城市？", img: "colosseum.jpg", options: ["羅馬", "雅典", "伊斯坦堡", "馬德里"], answer: "羅馬" },
  { cat: "travel", type: "image", q: "這座安地斯山上的印加古城位於哪個國家？", img: "machu.jpg", options: ["秘魯", "墨西哥", "智利", "哥倫比亞"], answer: "秘魯", explain: "馬丘比丘。" },
  { cat: "travel", type: "image", q: "這條由上千座朱紅鳥居組成的步道，位於日本哪個城市？", img: "inari.jpg", options: ["京都", "東京", "大阪", "奈良"], answer: "京都", explain: "伏見稻荷大社的「千本鳥居」。" },
  { cat: "travel", type: "image", q: "這座雕像位於哪個城市的港口？", img: "liberty.jpg", options: ["紐約", "舊金山", "波士頓", "巴黎"], answer: "紐約", explain: "自由女神像，由法國贈送給美國。" },
  { cat: "travel", type: "image", q: "這座直接在岩壁上雕鑿出的古城位於哪個國家？", img: "petra.jpg", options: ["約旦", "埃及", "沙烏地阿拉伯", "以色列"], answer: "約旦", explain: "佩特拉古城。" },
  { cat: "travel", type: "image", q: "照片中這座圓錐形的山是？", img: "fuji.jpg", options: ["富士山", "玉山", "吉力馬札羅山", "聖母峰"], answer: "富士山" },

  /* ==================== 猜歌 ==================== */
  { cat: "song", type: "single", q: "🎧 聽旋律猜歌名：", melody: "twinkle", options: ["小星星", "瑪莉有隻小綿羊", "兩隻老虎", "倫敦鐵橋垮下來"], answer: "小星星", explain: "旋律來自法國民謠，莫札特也曾以它寫過變奏曲。" },
  { cat: "song", type: "single", q: "🎧 聽旋律猜歌名：", melody: "joy", options: ["歡樂頌", "結婚進行曲", "給愛麗絲", "小蜜蜂"], answer: "歡樂頌", explain: "貝多芬《第九號交響曲》第四樂章。" },
  { cat: "song", type: "single", q: "🎧 聽旋律猜歌名：", melody: "tigers", options: ["兩隻老虎", "王老先生有塊地", "小星星", "生日快樂"], answer: "兩隻老虎", explain: "原曲是法國童謠〈Frère Jacques〉（雅克修士）。" },
  { cat: "song", type: "single", q: "🎧 聽旋律猜歌名：", melody: "london", options: ["倫敦鐵橋垮下來", "瑪莉有隻小綿羊", "聖誕鈴聲", "驪歌"], answer: "倫敦鐵橋垮下來" },
  { cat: "song", type: "single", q: "🎧 聽旋律猜曲名：", melody: "elise", options: ["給愛麗絲", "月光奏鳴曲", "小星星變奏曲", "土耳其進行曲"], answer: "給愛麗絲", explain: "貝多芬的鋼琴小品，在台灣常被垃圾車拿來播放。" },
  { cat: "song", type: "single", q: "🎧 聽旋律猜歌名：", melody: "jasmine", options: ["茉莉花", "望春風", "高山青", "小城故事"], answer: "茉莉花", explain: "中國江蘇民歌，普契尼的歌劇《杜蘭朵》也引用了這段旋律。" },
  { cat: "song", type: "single", q: "🎧 聽旋律猜歌名：", melody: "bee", options: ["小蜜蜂", "兩隻老虎", "小星星", "倫敦鐵橋垮下來"], answer: "小蜜蜂", explain: "這段德國民謠旋律在台灣也被填詞成〈蝴蝶〉。" },
  { cat: "song", type: "single", q: "🎧 聽旋律猜歌名（常在畢業典禮聽到）：", melody: "auld", options: ["驪歌（友誼萬歲）", "歡樂頌", "念故鄉", "奇異恩典"], answer: "驪歌（友誼萬歲）", explain: "原曲是蘇格蘭民謠〈Auld Lang Syne〉。" },
  { cat: "song", type: "single", q: "🎧 聽旋律猜歌名：", melody: "farm", options: ["王老先生有塊地", "瑪莉有隻小綿羊", "生日快樂", "小蜜蜂"], answer: "王老先生有塊地", explain: "原曲為〈Old MacDonald Had a Farm〉。" },
  { cat: "song", type: "single", q: "🎧 聽旋律，這是在什麼場合最常聽到的音樂？", melody: "wedding", options: ["婚禮", "畢業典禮", "生日派對", "運動會"], answer: "婚禮", explain: "華格納歌劇《羅恩格林》中的〈婚禮合唱〉，俗稱「結婚進行曲」。" },
  { cat: "song", type: "single", q: "🎧 聽聽看，這段旋律在台灣最常在哪裡聽到？", melody: "bell", options: ["學校上下課鐘聲", "垃圾車", "捷運進站", "便利商店開門"], answer: "學校上下課鐘聲", explain: "源自英國倫敦國會大廈大笨鐘的「西敏寺鐘聲」。" },
  { cat: "song", type: "single", q: "〈Bohemian Rhapsody〉（波希米亞狂想曲）是哪個樂團的作品？", options: ["皇后樂團 Queen", "披頭四 The Beatles", "滾石樂團 The Rolling Stones", "酷玩樂團 Coldplay"], answer: "皇后樂團 Queen" },
  { cat: "song", type: "single", q: "〈稻香〉是哪位歌手的作品？", options: ["周杰倫", "林俊傑", "王力宏", "陶喆"], answer: "周杰倫", explain: "收錄於 2008 年專輯《魔杰座》。" },
  { cat: "song", type: "single", q: "〈Let It Go〉是哪部迪士尼動畫電影的主題曲？", options: ["冰雪奇緣", "魔髮奇緣", "海洋奇緣", "可可夜總會"], answer: "冰雪奇緣" },
  { cat: "song", type: "single", q: "〈小幸運〉是哪部台灣電影的主題曲？", options: ["我的少女時代", "那些年，我們一起追的女孩", "痞子英雄", "我可能不會愛你"], answer: "我的少女時代", explain: "由田馥甄演唱。" },
  { cat: "song", type: "single", q: "傳奇樂團「披頭四」來自哪個城市？", options: ["英國利物浦", "英國倫敦", "美國紐約", "愛爾蘭都柏林"], answer: "英國利物浦" },
  { cat: "song", type: "short", q: "🎧 聽旋律，寫出歌名：", melody: "birthday", accept: ["生日快樂", "生日快樂歌", "祝你生日快樂", "happybirthday", "happybirthdaytoyou"] },
  { cat: "song", type: "short", q: "🎧 聽旋律，寫出歌名：", melody: "mary", accept: ["瑪莉有隻小綿羊", "瑪麗有隻小綿羊", "瑪莉有隻小羊", "瑪麗有隻小羊", "小綿羊", "maryhadalittlelamb"] },
  { cat: "song", type: "short", q: "🎧 聽旋律，寫出歌名：", melody: "jingle", accept: ["聖誕鈴聲", "jinglebells", "叮叮噹", "鈴兒響叮噹", "叮叮噹叮叮噹"] },
  { cat: "song", type: "short", q: "🎧 這段旋律常被填詞為〈念故鄉〉，原曲出自德弗札克哪一號交響曲？（填數字）", melody: "largo", accept: ["9", "九", "第九號", "第九", "新世界", "新世界交響曲", "第9號"], explain: "德弗札克《第九號交響曲「新世界」》第二樂章。" },
  { cat: "song", type: "qa", q: "為什麼〈兩隻老虎〉可以用「輪唱」的方式演唱？", melody: "tigers", ref: "因為它的原曲〈Frère Jacques〉本來就是一首「卡農（輪唱曲）」：旋律分成四句，每句和聲上都能互相搭配，所以第二人晚一句開始唱同一段旋律，疊在一起依然和諧。" },
  { cat: "song", type: "qa", q: "〈歡樂頌〉出自哪位作曲家的哪部作品？歌詞又來自誰？", melody: "joy", ref: "出自貝多芬《第九號交響曲》第四樂章（1824 年首演），歌詞取自德國詩人席勒的詩〈歡樂頌〉（An die Freude）。今日也是歐盟的盟歌。" },
  { cat: "song", type: "image", q: "看表情符號猜兒歌：", emoji: "⭐✨🌙😴", options: ["小星星", "搖嬰仔歌", "月亮代表我的心", "虹彩妹妹"], answer: "小星星" },
  { cat: "song", type: "image", q: "看表情符號猜歌：", emoji: "🎂🕯️🎉🎁", options: ["生日快樂歌", "恭喜恭喜", "歡樂頌", "新年好"], answer: "生日快樂歌" },
  { cat: "song", type: "image", q: "看表情符號猜歌：", emoji: "🔔🦌🛷🎄", options: ["聖誕鈴聲", "平安夜", "小星星", "我們祝你聖誕快樂"], answer: "聖誕鈴聲", explain: "Jingle Bells —— 鈴鐺、雪橇。" },
  { cat: "song", type: "image", q: "看表情符號猜兒歌：", emoji: "👧🐑🏫", options: ["瑪莉有隻小綿羊", "王老先生有塊地", "三隻小豬", "小毛驢"], answer: "瑪莉有隻小綿羊", explain: "小綿羊跟著瑪莉去上學。" },

  /* ==================== 猜謎 ==================== */
  { cat: "riddle", type: "single", q: "字謎：「一口咬掉牛尾巴」（打一字）", options: ["告", "吽", "午", "先"], answer: "告", explain: "「牛」去掉尾巴，加上「口」。" },
  { cat: "riddle", type: "single", q: "字謎：「千里相逢」（打一字）", options: ["重", "量", "埋", "童"], answer: "重", explain: "「千」與「里」上下相疊。" },
  { cat: "riddle", type: "single", q: "字謎：「森林失火」（打一字）", options: ["焚", "炎", "燊", "災"], answer: "焚", explain: "「林」下面一把「火」。" },
  { cat: "riddle", type: "single", q: "字謎：「上下一體」（打一字）", options: ["卡", "正", "王", "土"], answer: "卡", explain: "上 + 下 =「卡」。" },
  { cat: "riddle", type: "single", q: "腦筋急轉彎：什麼東西越洗越髒？", options: ["水", "衣服", "碗", "毛巾"], answer: "水" },
  { cat: "riddle", type: "single", q: "腦筋急轉彎：一年之中，哪個月有 28 天？", options: ["每個月都有", "只有二月", "二月和十二月", "沒有任何月份"], answer: "每個月都有" },
  { cat: "riddle", type: "single", q: "腦筋急轉彎：小明的爸爸有三個兒子，老大叫大毛、老二叫二毛，老三叫什麼？", options: ["小明", "三毛", "小毛", "老毛"], answer: "小明" },
  { cat: "riddle", type: "single", q: "腦筋急轉彎：有個人從飛機上跳下來卻毫髮無傷，為什麼？", options: ["飛機停在地面上", "他有超能力", "他掉進海裡", "他是鳥人"], answer: "飛機停在地面上" },
  { cat: "riddle", type: "single", q: "腦筋急轉彎：什麼東西有很多牙齒，卻從來不咬人？", options: ["梳子", "鯊魚", "鱷魚", "牙醫"], answer: "梳子" },
  { cat: "riddle", type: "single", q: "邏輯題：3 隻貓 3 分鐘可以抓 3 隻老鼠。照這個速度，100 隻貓抓 100 隻老鼠要幾分鐘？", options: ["3 分鐘", "100 分鐘", "33 分鐘", "1 分鐘"], answer: "3 分鐘", explain: "每隻貓 3 分鐘抓 1 隻，100 隻貓同時抓，3 分鐘就抓到 100 隻。" },
  { cat: "riddle", type: "single", q: "邏輯題：賽跑中你超過了第二名，你現在是第幾名？", options: ["第二名", "第一名", "第三名", "最後一名"], answer: "第二名", explain: "你取代了第二名的位置，第一名還在前面喔！" },
  { cat: "riddle", type: "short", q: "字謎：「日月同輝」（打一字）", accept: ["明"] },
  { cat: "riddle", type: "short", q: "字謎：「二人頂破天」（打一字）", accept: ["夫"], explain: "「二」+「人」，人的頭頂穿過了「天」的上面一橫。" },
  { cat: "riddle", type: "short", q: "字謎：「一人一張口，口下長隻手」（打一字）", accept: ["拿"], explain: "人 + 一 + 口 =「合」，下面再加「手」。" },
  { cat: "riddle", type: "short", q: "腦筋急轉彎：什麼門永遠都關不起來？", accept: ["球門", "足球門"] },
  { cat: "riddle", type: "short", q: "腦筋急轉彎：什麼路最窄？（四字成語）", accept: ["冤家路窄"] },
  { cat: "riddle", type: "qa", q: "經典邏輯題：農夫要帶一匹狼、一隻羊和一顆白菜過河，船一次只能載農夫和一樣東西。農夫不在時，狼會吃羊、羊會吃菜。該怎麼安排？", ref: "①帶羊過河 → ②空手回來 → ③帶狼過河 → ④把羊帶回來 → ⑤帶白菜過河 → ⑥空手回來 → ⑦再帶羊過河。（第 3 步也可以先帶白菜，對應地第 5 步改帶狼。）關鍵是：羊不能和狼或菜單獨留下，所以要把羊「帶回來」一次。" },
  { cat: "riddle", type: "qa", q: "想一想：為什麼照鏡子時看起來「左右顛倒」，上下卻不會顛倒？", ref: "鏡子其實沒有左右顛倒，它反轉的是「前後」（垂直鏡面的方向）。我們覺得左右相反，是因為想像自己轉身走到鏡子裡的位置——人習慣繞著垂直軸轉身，於是左右互換；如果想像自己翻跟斗倒立進去，就會覺得是上下顛倒了。" },
  { cat: "riddle", type: "image", q: "看圖猜成語：", emoji: "1️⃣🪨2️⃣🐦", options: ["一石二鳥", "一箭雙鵰", "鳥語花香", "石沉大海"], answer: "一石二鳥" },
  { cat: "riddle", type: "image", q: "看圖猜成語：", emoji: "🖌️🐍➕🦶", options: ["畫蛇添足", "打草驚蛇", "虎頭蛇尾", "杯弓蛇影"], answer: "畫蛇添足" },
  { cat: "riddle", type: "image", q: "看圖猜成語：", emoji: "🐄🎹🎶", options: ["對牛彈琴", "九牛一毛", "汗牛充棟", "庖丁解牛"], answer: "對牛彈琴" },
  { cat: "riddle", type: "image", q: "看圖猜成語：", emoji: "🕳️🐸👀", options: ["井底之蛙", "青蛙王子", "坐井觀天", "蛙鳴蟬噪"], answer: "井底之蛙", explain: "「坐井觀天」意思接近，但圖裡主角是青蛙喔！" },
  { cat: "riddle", type: "image", q: "看圖猜成語：", emoji: "🐔🗣️🦆", options: ["雞同鴨講", "雞飛狗跳", "聞雞起舞", "呆若木雞"], answer: "雞同鴨講" },
  { cat: "riddle", type: "image", q: "看圖猜成語：", emoji: "🌳🧍⏳🐇", options: ["守株待兔", "狡兔三窟", "龜兔賽跑", "兔死狐悲"], answer: "守株待兔" },

  /* ==================== 動物生活 ==================== */
  { cat: "animal", type: "single", q: "地球上體型最大的動物是？", options: ["藍鯨", "非洲象", "鯨鯊", "大王魷"], answer: "藍鯨", explain: "成年藍鯨體長可達約 30 公尺。" },
  { cat: "animal", type: "single", q: "陸地上跑得最快的動物是？", options: ["獵豹", "獅子", "鴕鳥", "羚羊"], answer: "獵豹", explain: "短距離衝刺時速可達 100 公里以上。" },
  { cat: "animal", type: "single", q: "無尾熊主要吃什麼？", options: ["尤加利葉", "竹子", "香蕉", "昆蟲"], answer: "尤加利葉", explain: "尤加利葉營養低，所以無尾熊一天要睡將近 20 小時。" },
  { cat: "animal", type: "single", q: "章魚有幾顆心臟？", options: ["3 顆", "1 顆", "2 顆", "8 顆"], answer: "3 顆", explain: "兩顆負責把血送到鰓，一顆送到全身；牠的血是藍色的。" },
  { cat: "animal", type: "single", q: "蝙蝠屬於哪一類動物？", options: ["哺乳類", "鳥類", "爬蟲類", "昆蟲"], answer: "哺乳類", explain: "牠是唯一能真正飛行的哺乳類。" },
  { cat: "animal", type: "single", q: "長頸鹿的脖子有幾節頸椎？", options: ["7 節", "12 節", "20 節", "3 節"], answer: "7 節", explain: "和人類一樣！只是每一節都特別長。" },
  { cat: "animal", type: "single", q: "下列哪一種動物是會「下蛋」的哺乳類？", options: ["鴨嘴獸", "袋鼠", "海豚", "蝙蝠"], answer: "鴨嘴獸", explain: "單孔目的鴨嘴獸與針鼴是現存唯二的卵生哺乳類。" },
  { cat: "animal", type: "single", q: "蜜蜂發現花蜜後，用什麼方式告訴同伴花在哪裡？", options: ["跳搖擺舞", "發出叫聲", "留下腳印", "噴出顏色"], answer: "跳搖擺舞", explain: "又稱「8 字舞」，舞動的角度與時間代表方向與距離。" },
  { cat: "animal", type: "single", q: "駱駝背上的駝峰主要儲存什麼？", options: ["脂肪", "水", "血液", "空氣"], answer: "脂肪", explain: "脂肪可以在食物缺乏時轉換成能量。" },
  { cat: "animal", type: "single", q: "鯊魚的骨骼主要由什麼構成？", options: ["軟骨", "硬骨", "甲殼", "沒有骨骼"], answer: "軟骨" },
  { cat: "animal", type: "single", q: "蝴蝶可以用身體的哪個部位「嘗味道」？", options: ["腳", "翅膀", "觸角", "眼睛"], answer: "腳", explain: "牠們腳上有味覺感受器，降落時就能判斷能否產卵或進食。" },
  { cat: "animal", type: "single", q: "台灣黑熊和許多北方的熊不同，牠們通常會冬眠嗎？", options: ["通常不冬眠", "一定冬眠半年", "只有公熊冬眠", "夏天才休眠"], answer: "通常不冬眠", explain: "台灣氣候較溫暖、冬天仍找得到食物，所以台灣黑熊一般不冬眠。" },
  { cat: "animal", type: "short", q: "台灣特有亞種、胸前有 V 字形白色斑紋的熊叫什麼？", accept: ["台灣黑熊", "黑熊", "月熊", "亞洲黑熊"] },
  { cat: "animal", type: "short", q: "常被稱為「萬獸之王」或「草原之王」的動物是？", accept: ["獅子", "獅", "非洲獅"] },
  { cat: "animal", type: "short", q: "蝌蚪長大後會變成什麼？", accept: ["青蛙", "蛙", "蟾蜍", "青蛙或蟾蜍"] },
  { cat: "animal", type: "short", q: "生活在南極、不會飛卻很會游泳的鳥是？", accept: ["企鵝", "帝王企鵝", "皇帝企鵝", "阿德利企鵝"] },
  { cat: "animal", type: "qa", q: "許多動物會「遷徙」，原因是什麼？請舉一個例子。", ref: "動物遷徙多半是為了①尋找食物與水、②避開嚴寒或乾季、③到安全的地方繁殖。例：東非角馬隨雨季在塞倫蓋提與馬賽馬拉之間遷徙；鮭魚洄游回出生的河川產卵；台灣的紫斑蝶冬天南遷到茂林越冬；灰面鵟鷹每年春秋過境台灣。" },
  { cat: "animal", type: "qa", q: "什麼是「擬態」？請舉例說明。", ref: "擬態是生物在外形、顏色或行為上模仿其他生物或環境，用來躲避天敵或獵捕獵物。例：竹節蟲像樹枝、枯葉蝶像落葉（偽裝）；無毒的食蚜蠅長得像會螫人的蜜蜂（貝氏擬態）；比目魚改變體色融入海底。" },
  { cat: "animal", type: "qa", q: "我們可以在日常生活中做哪些事來保護野生動物？", ref: "例如：不購買象牙、穿山甲鱗片等野生動物製品；不棄養寵物、不放生外來種；減少塑膠使用避免海洋生物誤食；開車經過山區減速，留意路殺；不餵食野生動物；支持保育團體或參與淨灘、生態調查。" },
  { cat: "animal", type: "image", q: "這隻臀部有斑馬紋的動物，其實是哪種動物的近親？", img: "okapi.jpg", options: ["長頸鹿", "斑馬", "馬", "羚羊"], answer: "長頸鹿", explain: "牠是「霍加狓」，生活在剛果的雨林中。" },
  { cat: "animal", type: "image", q: "這種一輩子保持幼體外型、能再生肢體的兩棲類，俗稱什麼？", img: "axolotl.jpg", options: ["六角恐龍", "娃娃魚", "蠑螈王", "海蛞蝓"], answer: "六角恐龍", explain: "正式名稱是「墨西哥鈍口螈」。" },
  { cat: "animal", type: "image", q: "這隻動物的名字是？", img: "redpanda.jpg", options: ["小貓熊（小熊貓）", "浣熊", "狐狸", "貂"], answer: "小貓熊（小熊貓）", explain: "牠和大貓熊（大熊貓）一樣愛吃竹子，但並不是近親。" },
  { cat: "animal", type: "image", q: "這隻有鴨子般嘴巴的動物是？", img: "platypus.jpg", options: ["鴨嘴獸", "水獺", "河狸", "海獅"], answer: "鴨嘴獸", explain: "公鴨嘴獸後腳有毒刺。" },
  { cat: "animal", type: "image", q: "這種全身覆蓋鱗片、遇到危險會捲成一團的動物是？", img: "pangolin.jpg", options: ["穿山甲", "犰狳", "刺蝟", "食蟻獸"], answer: "穿山甲", explain: "台灣也有特有亞種「中華穿山甲」，是受保育的動物。" },
  { cat: "animal", type: "image", q: "這種生活在高山、有著粗長尾巴的大貓是？", img: "snowleopard.jpg", options: ["雪豹", "花豹", "獵豹", "雲豹"], answer: "雪豹" },
  { cat: "animal", type: "image", q: "這種長著一根長長「角」的北極鯨類叫什麼？", img: "narwhal.jpg", options: ["一角鯨", "劍旗魚", "白鯨", "虎鯨"], answer: "一角鯨", explain: "那根「角」其實是一顆長長的牙齒。" },
  { cat: "animal", type: "image", q: "這隻號稱「世界上最快樂的動物」、住在澳洲羅特尼斯島的有袋類是？", img: "quokka.jpg", options: ["短尾矮袋鼠", "無尾熊", "袋熊", "負鼠"], answer: "短尾矮袋鼠", explain: "英文叫 Quokka，嘴角看起來總像在微笑。" },
  { cat: "animal", type: "image", q: "這隻動物是？", img: "blackbear.jpg", options: ["台灣黑熊", "馬來熊", "棕熊", "北極熊"], answer: "台灣黑熊" },
  { cat: "animal", type: "image", q: "這種世界上最大的齧齒類動物叫什麼？", img: "capybara.jpg", options: ["水豚", "河狸", "天竺鼠", "土撥鼠"], answer: "水豚" },
];
